abufsrc@Music=outputs=1:map=1[Music0],
[Music0]asubgraph@MusicConvert=inputs=1:outputs=1:map=1[Music1],
[Music1]adevsink@pcm0p=format=nuttx:sample_fmt=s16:sample_rate=24000:ch_layout=mono:devname=/dev/audio/pcm0p;
<subgraph>MusicConvert:[in]aresample=osr=24000:osf=s16:ochl=mono[out]
